language: go
go:
  - 1.7.4
  - 1.6.3

sudo: false

before_install:
  - git config --global url."https://".insteadOf git://
  - go get -u github.com/golang/lint/golint
  - mkdir -p $GOPATH/src/github.com/vbatts && ln -sf $(pwd) $GOPATH/src/github.com/vbatts/go-mtree
  - go get ./...

install: true

script:
  - make validation
  - make validation.tags
